### PR TITLE
Add delete button admin

### PR DESCRIPTION
**Pull request by scornelissen85**
This PR add an extra delete button in admin interface to delete manually instance from admin interface.

### CODE REVIEW

**Comment by J12934** [comment]
Hi 👋
This sounds and looks really cool 👍

Will take a closer look and try to get it running tomorrow!

**Comment by J12934** [comment]
Look and works great!

Thank you very much 🎉

**Comment by J12934** [comment]
I will push out a release soon.

The CI setups is currently unfortunately not set up. 
Its running with the new Github Action which we don't have enabled in this org. Might have to migrate to something else for now, or just build the images by hand.

**Comment by J12934** [comment]
I updated the JuiceBalancer latest tag.
Your changes are now included in the default installation 😉

Will push out a proper 1.2 release as soon as i get Github Actions up and running again.

**Comment by scornelissen85** [comment]
Great, thanks :clap:

**Pull request merged**
