### PR TITLE
Pass NODE_ENV to JuiceShop

### PR DESCRIPTION
**Pull request by scornelissen85**
Add support for passing a custom NODE_ENV environment variable to JuiceShop

### CODE REVIEW

**Comment by J12934** [comment]
I'M guessing this is mostly to use one of the predefined config yamls?

Having a fixed `NODE_ENV` was conscious choice, to enable the ability to pass a complete "Juice Shop config yaml" in the helm charts values. To use one of the predefined configs I'd personally prefer just to copy it over into my helm `values.yaml`. This way I'd be easily able to change any of the default values.

Are there any use cases where this wouldn't work or totally suck?

**Comment by scornelissen85** [comment]
We used a custom image with a custom configuration. This configuration can be used by setting the right `NODE_ENV`.

**Comment by J12934** [comment]
The ting i really wan't to avoid is that people change the node_env to something other than `juicy-ctf` without realising that this will mean that their Juice Shop config in their helm config will not be used. Especially since node developer are used to always wanting to make sure that node_env is set to `production`.

To make sure that doesn't happen I think that the nodeEnv option and config option in the helm values files should be right next to each other, plus the nodeEnv Option should have a short explanatory comment over it, explaining that changing it will mean that the provided config will no longer be picked up.

**Comment by J12934** [comment]
Nice 👍
Thank you. Will try to merge this and push out a release tomorrow.

**Comment by scornelissen85** [comment]
Thank you. This was the latest change I have currently made.

**Pull request merged**
